name: asttro
description: Seu aplicativo Flutter.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  lucide_icons_flutter: ^3.0.8
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf

flutter_native_splash:
  android: true
  ios: true
  web: false

  fullscreen: true
  # Splash padrão (Android < 12 e iOS)
  color: "#0D0D1B"
  image: assets/logo/logo_512.png

  android_12:
    # Fundo do splash
    color: "#0D0D1B"

    # Ícone central sem fundo
    image: assets/logo/logo_1152.png

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/logo/logo_1024.png"
  adaptive_icon_foreground: "assets/logo/logo_1024.png"
  adaptive_icon_background: "#061637"